import { type RouteConfig, route, index, layout } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("about", "routes/about.tsx"),
  route("articles", "routes/articles._index.tsx"),
  route("articles/:slug", "routes/articles.$slug.tsx"),
  route("contact", "routes/contact.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  // Design system (ADR-021): one page per foundation, primitive, component and
  // block. Paths written out in full: app/routes/design-system-route.test.ts
  // reads them straight from this file.
  layout("routes/design-system._layout.tsx", [
    route("design-system", "routes/design-system._index.tsx"),
    // foundations
    route("design-system/foundations", "routes/design-system.foundations._index.tsx"),
    route("design-system/foundations/color", "routes/design-system.foundations.color.tsx"),
    route("design-system/foundations/elevation", "routes/design-system.foundations.elevation.tsx"),
    route("design-system/foundations/icons", "routes/design-system.foundations.icons.tsx"),
    route("design-system/foundations/motion", "routes/design-system.foundations.motion.tsx"),
    route("design-system/foundations/spacing", "routes/design-system.foundations.spacing.tsx"),
    route("design-system/foundations/typography", "routes/design-system.foundations.typography.tsx"),
    // primitives
    route("design-system/primitives", "routes/design-system.primitives._index.tsx"),
    route("design-system/primitives/accordion", "routes/design-system.primitives.accordion.tsx"),
    route("design-system/primitives/alerts", "routes/design-system.primitives.alerts.tsx"),
    route("design-system/primitives/avatar", "routes/design-system.primitives.avatar.tsx"),
    route("design-system/primitives/badges", "routes/design-system.primitives.badges.tsx"),
    route("design-system/primitives/breadcrumbs", "routes/design-system.primitives.breadcrumbs.tsx"),
    route("design-system/primitives/buttons", "routes/design-system.primitives.buttons.tsx"),
    route("design-system/primitives/cards", "routes/design-system.primitives.cards.tsx"),
    route("design-system/primitives/dialog", "routes/design-system.primitives.dialog.tsx"),
    route("design-system/primitives/dropdown-menu", "routes/design-system.primitives.dropdown-menu.tsx"),
    route("design-system/primitives/empty-state", "routes/design-system.primitives.empty-state.tsx"),
    route("design-system/primitives/form-field", "routes/design-system.primitives.form-field.tsx"),
    route("design-system/primitives/inputs", "routes/design-system.primitives.inputs.tsx"),
    route("design-system/primitives/layout", "routes/design-system.primitives.layout.tsx"),
    route("design-system/primitives/page-header", "routes/design-system.primitives.page-header.tsx"),
    route("design-system/primitives/pagination", "routes/design-system.primitives.pagination.tsx"),
    route("design-system/primitives/popover", "routes/design-system.primitives.popover.tsx"),
    route("design-system/primitives/radio-group", "routes/design-system.primitives.radio-group.tsx"),
    route("design-system/primitives/sheet", "routes/design-system.primitives.sheet.tsx"),
    route("design-system/primitives/skeleton", "routes/design-system.primitives.skeleton.tsx"),
    route("design-system/primitives/stat-card", "routes/design-system.primitives.stat-card.tsx"),
    route("design-system/primitives/table", "routes/design-system.primitives.table.tsx"),
    route("design-system/primitives/tabs", "routes/design-system.primitives.tabs.tsx"),
    route("design-system/primitives/toast", "routes/design-system.primitives.toast.tsx"),
    route("design-system/primitives/toggle", "routes/design-system.primitives.toggle.tsx"),
    route("design-system/primitives/tooltip", "routes/design-system.primitives.tooltip.tsx"),
    // components
    route("design-system/components", "routes/design-system.components._index.tsx"),
    route("design-system/components/article-card", "routes/design-system.components.article-card.tsx"),
    route("design-system/components/error-page", "routes/design-system.components.error-page.tsx"),
    route("design-system/components/footer", "routes/design-system.components.footer.tsx"),
    route("design-system/components/header", "routes/design-system.components.header.tsx"),
    route("design-system/components/page-hero", "routes/design-system.components.page-hero.tsx"),
    route("design-system/components/wordmark", "routes/design-system.components.wordmark.tsx"),
    // blocks
    route("design-system/blocks", "routes/design-system.blocks._index.tsx"),
    route("design-system/blocks/about", "routes/design-system.blocks.about.tsx"),
    route("design-system/blocks/articles", "routes/design-system.blocks.articles.tsx"),
    route("design-system/blocks/contact", "routes/design-system.blocks.contact.tsx"),
    route("design-system/blocks/content", "routes/design-system.blocks.content.tsx"),
    route("design-system/blocks/cta", "routes/design-system.blocks.cta.tsx"),
    route("design-system/blocks/faq", "routes/design-system.blocks.faq.tsx"),
    route("design-system/blocks/features", "routes/design-system.blocks.features.tsx"),
    route("design-system/blocks/gallery", "routes/design-system.blocks.gallery.tsx"),
    route("design-system/blocks/hero-simple", "routes/design-system.blocks.hero-simple.tsx"),
    route("design-system/blocks/hero", "routes/design-system.blocks.hero.tsx"),
    route("design-system/blocks/image-text", "routes/design-system.blocks.image-text.tsx"),
    route("design-system/blocks/newsletter", "routes/design-system.blocks.newsletter.tsx"),
    route("design-system/blocks/stats", "routes/design-system.blocks.stats.tsx"),
    route("design-system/blocks/team", "routes/design-system.blocks.team.tsx"),
    route("design-system/blocks/testimonials", "routes/design-system.blocks.testimonials.tsx"),
  ]),
  route("sitemap.xml", "routes/[sitemap.xml].tsx"),
  route("*", "routes/$.tsx"),
] satisfies RouteConfig;
